### ISSUE TITLE
未インストールにもかかわらず既にインストールされているというエラーが起きる

### ISSUE THREAD

**Issue by Yamase7** [tackme31/howmessy#1]
vsixファイルをダウンロードしてインストールしようとしましたが、「この拡張機能は、現在インストール済みの製品にはインストールできません。」というエラーでインストールできませんでした。

以下にエラー発生時のログを添付いたします。
[howmessy_VSIXInstaller_error_20220315.log](https://github.com/tackme31/howmessy/files/8251067/howmessy_VSIXInstaller_error_20220315.log)

**Comment by tackme31** [comment]
@Yamase7 
ご報告ありがとうございます。
エラーを確認したところ、お使いのVisual Studioでは本拡張機能をサポートしていない可能性があります。
お使いのVisual Studioのバージョン情報をご提供頂いてもよろしいでしょうか？

**Comment by Yamase7** [comment]
@tackme31
失礼いたしました。
VisualStudio 2022 のみのサポートというのを見逃してしまいました。
使用したのはVisualStudio 2019 Professionalです。
対応ありがとうございます。
